# 50 SELECTs on an LIKE comparison.  There is no index so a full table scan is required.
#
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%zero%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%one%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%two%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%three%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%four%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%five%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%six%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%seven%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%eight%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%nine%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%ten%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%eleven%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%twelve%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%thirteen%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%fourteen%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%fifteen%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%sixteen%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%seventeen%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%eighteen%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%nineteen%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%twenty%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%twenty one%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%twenty two%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%twenty three%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%twenty four%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%twenty five%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%twenty six%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%twenty seven%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%twenty eight%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%twenty nine%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%thirty%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%thirty one%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%thirty two%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%thirty three%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%thirty four%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%thirty five%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%thirty six%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%thirty seven%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%thirty eight%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%thirty nine%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%forty%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%forty one%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%forty two%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%forty three%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%forty four%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%forty five%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%forty six%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%forty seven%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%forty eight%';
SELECT count(*), avg(b) FROM t1 WHERE c LIKE '%forty nine%';